tasks:
  - before: ./install.sh
    init: npm install
    command: npm run serve-gitpod

ports:
  # - port: 3000
  # onOpen: open-preview
  - port: 8888
    onOpen: ignore

image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - gulajavaministudio.mayukaithemevsc
    - eamodio.gitlens
    - naumovs.color-highlight
    - bierner.color-info
    - anseki.vscode-color
    - EditorConfig.EditorConfig
    - dbaeumer.vscode-eslint
    - christian-kohler.path-intellisense
    - evgeniypeshkov.syntax-highlighter
